### ISSUE TITLE
'unsafe-eval' error when running 'uglify' from atom command pallete

### ISSUE THREAD

**Issue by smiffy6969** [sindresorhus/atom-uglify#9]
Refused to evaluate a string as JavaScript because 'unsafe-eval'.....

This is the error I am getting (on this and other packages) when I try to run uglify command in atom, this is really weird because I have been getting this a lot since I reinstalled ubuntu gnome. I pulled in atom from the repo as usual... node is updated to latest, I have tested and can run uglifyjs from command line (which I believe you guys use???) but for some reason I get this error on a few packages now.

The full error is...

Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

Now i am aware of the details surrounding this error... but I am at a loss if it is me, or this package (and others) at fault.

thanks

Paul

**Comment by smiffy6969** [comment]
Running ubuntu gnome (15.10..... yes i know its beta ;)) atom latest 1.0.19, node 4.0.0

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
  at Function (native)
  at Object.<anonymous> (/home/paul/.atom/packages/uglify/node_modules/uglify-js/tools/node.js:24:4)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/home/paul/.atom/packages/uglify/index.js:9:17)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:761:34)
  at Package.module.exports.Package.activateConfig (/usr/share/atom/resources/app.asar/src/package.js:263:14)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:241:14)
  at /usr/share/atom/resources/app.asar/src/package.js:838:25
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:226:20)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:245:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:184:20)

**Comment by smiffy6969** [comment]
Works great now, thanks..... would be perfect if I didnt have to have 20 attempts to update.... dumb as DDOS prevention settings playing having with github at the mo, timeouts everywhere....
